name: CI/CD for React App with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
          build-args: |
            VITE_API_URL=https://api.moclawr.com
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy locally
        run: |
          # Stop and remove existing container if it exists
          docker stop portfolio 2>/dev/null || echo "Container portfolio not running"
          docker rm portfolio 2>/dev/null || echo "Container portfolio not found"
          
          # Pull the latest image
          docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
          
          # Run the new container
          docker run -d --restart always --name portfolio -p 5300:80 \
            -e VITE_API_URL=https://api.moclawr.com \
            ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
          
          # Verify container is running
          sleep 5
          docker ps | grep portfolio || echo "Warning: Container may not be running properly"
