name: CI/CD for React App with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/portfolio:latest
          build-args: |
            VITE_API_URL=https://api.moclawr.com
          platforms: ${{ github.event_name == 'push' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/portfolio:buildcache
            type=gha
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/portfolio:buildcache,mode=max
            type=gha,mode=max

      - name: Deploy locally
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Stop and remove existing container if it exists
          docker stop portfolio 2>/dev/null || echo "Container portfolio not running"
          docker rm portfolio 2>/dev/null || echo "Container portfolio not found"
          
          # Pull the latest image
          docker pull ghcr.io/${{ github.repository_owner }}/portfolio:latest
          
          # Run the new container
          docker run -d --restart always --name portfolio -p 5300:80 \
            -e VITE_API_URL=https://api.moclawr.com \
            ghcr.io/${{ github.repository_owner }}/portfolio:latest
          
          # Verify container is running
          sleep 5
          docker ps | grep portfolio || echo "Warning: Container may not be running properly"
